name: Docker Build Test
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Yeh line manual button enable karegi

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Simple Echo Test
        run: echo "GitHub Actions is working!"